language: java

jdk:
  - openjdk8
  

job:
  include:
    - stage: "Compile"
      name: "Compile"
      script: ./mvnw clean package -DskipTests
    - stage: "Tests"
      name: "Tests"
      script: ./mvnw test
      
      
notifications:
  email: dipan.cs@gmail.com
