language: java
jdk:
  - openjdk8

services:
  - docker
addons:
  sonarcloud:
    organization: "dipans"
    token:
      secure: 50b467086340bb2b698715848d47326dbd8a9b54
      

script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=dipans_demo-cicd

notifications:
  email: dipan.cs@gmail.com
