language: java
jdk:
<<<<<<< HEAD
  - openjdk8
  
  
=======
- openjdk8
services:
- docker
>>>>>>> 9f10133b0d04ed802e1da09bc7ec41ce555cb2df
addons:
  sonarcloud:
    organization: "dipans"
    token:
<<<<<<< HEAD
      secure:  travis encrypt 435d2cb0eb8e17fcb03713b12f720e4e23c77c38 #"**************************" # encrypted value of your token
      
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=dipans_demo-cicd

stages:
  - compile
  - test
  - codecov 

job:
  include:
    - stage: compile
      name: "Compile"
      script: ./mvnw clean package -DskipTests
    - stage: test
      name: "Test"
      script: ./mvnw test
    - stage: codecov
      name: "Code Coverage"
      script: ./mvnw cobertura:cobertura
      
after_success:
  - bash <(curl -s https://codecov.io/bash)
      
=======
      secure: 50b467086340bb2b698715848d47326dbd8a9b54
script:
- "./mvnw clean install -B"
- "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=dipans_demo-cicd"
>>>>>>> 9f10133b0d04ed802e1da09bc7ec41ce555cb2df
notifications:
  email: dipan.cs@gmail.com
