language: java

jdk:
  - openjdk8

stages:
  - compile
  - test  

job:
  include:
    - stage: compile
      name: "Compile"
      script: ./mvnw clean package -DskipTests
    - stage: test
      name: "Test"
      script: ./mvnw test
      
      
notifications:
  email: dipan.cs@gmail.com
