language: java

jdk:
  - openjdk8

stages:
  - compile
  - test
  - codecov 

job:
  include:
    - stage: compile
      name: "Compile"
      script: ./mvnw clean package -DskipTests
    - stage: test
      name: "Test"
      script: ./mvnw test
    - stage: codecov
      name: "Code Coverage"
      script: ./mvnw cobertura:cobertura
      
      
notifications:
  email: dipan.cs@gmail.com
