FROM openjdk:8-jdk-alpine

LABEL maintainer="dipan.cs@gmail.com"

VOLUME /tmp

EXPOSE 9090

ARG JAR_FILE=target/demo-cicd-0.0.1-SNAPSHOT.jar

ADD ${JAR_FILE} demo-cicd.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/demo-cicd.jar"]